jwt:
  get:
    token:
      uri: /user/login
  secret: nnpro
server:
  port: 9000
  servlet:
    context-path: /api/v1
spring:
  datasource:
    password: nnpia
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
todoexpiration: 12

graphql:
  graphiql:
    enable: true
    path: /graphiql
  path: /graphql

